[package]
name = "cailoxo"
version = "0.2.2"
edition = "2024"
license = "MIT"
description = "Adaptive native prompt generator"
repository = "https://github.com/vufly/cailoxo"
readme = "README.md"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
toml = "0.9.8"
