use std::fmt::Write;

use anyhow::Result;

use crate::config::{Config, Span};

use super::shared::{
    STATUSES, ansi_pair, color_escape, git_branch_icon, icon_pairs, layout, status_separator,
    status_template,
};

const RESET: &str = "\u{1b}[0m";

pub fn generate(config: &Config) -> Result<String> {
    let layout = layout(config)?;
    let os = layout.os;
    let path = layout.path;
    let git = layout.git;
    let prompt = layout.prompt_span;

    let os_style = ansi_pair(os.foreground.as_ref(), os.background.as_ref())?;
    let path_style = ansi_pair(path.foreground.as_ref(), path.background.as_ref())?;
    let git_clean_style = ansi_pair(git.foreground.as_ref(), git.background.as_ref())?;
    let git_dirty_style = ansi_pair(
        git.foreground.as_ref(),
        git.dirty_background.as_ref().or(git.background.as_ref()),
    )?;
    let os_tail = edge(
        os.tail.as_deref(),
        os.background.as_ref(),
        path.background.as_ref(),
        os.invert_tail,
    )?;
    let path_sep_clean = edge(
        path.separator.as_deref(),
        path.background.as_ref(),
        git.background.as_ref(),
        path.invert_separator,
    )?;
    let path_sep_dirty = edge(
        path.separator.as_deref(),
        path.background.as_ref(),
        git.dirty_background.as_ref().or(git.background.as_ref()),
        path.invert_separator,
    )?;
    let path_sep_last = edge(
        path.separator.as_deref().or(path.tail.as_deref()),
        path.background.as_ref(),
        None,
        path.invert_separator || path.invert_tail,
    )?;
    let git_sep_clean = edge(
        git.separator.as_deref(),
        git.background.as_ref(),
        None,
        git.invert_separator,
    )?;
    let git_sep_dirty = edge(
        git.separator.as_deref(),
        git.dirty_background.as_ref().or(git.background.as_ref()),
        None,
        git.invert_separator,
    )?;
    let prompt_ok_style = ansi_pair(prompt.success_foreground.as_ref(), None)?;
    let prompt_error_style = ansi_pair(prompt.error_foreground.as_ref(), None)?;

    let transient = config.transient.as_ref();
    let transient_enabled = transient.is_some_and(|transient| transient.enabled);
    let transient_template = transient
        .map(|transient| transient.template.as_str())
        .filter(|template| !template.is_empty())
        .unwrap_or(&prompt.template);
    let transient_ok_style = ansi_pair(
        transient
            .and_then(|transient| transient.success_foreground.as_ref())
            .or(prompt.success_foreground.as_ref()),
        transient.and_then(|transient| transient.background.as_ref()),
    )?;
    let transient_error_style = ansi_pair(
        transient
            .and_then(|transient| transient.error_foreground.as_ref())
            .or(prompt.error_foreground.as_ref()),
        transient.and_then(|transient| transient.background.as_ref()),
    )?;

    let mut script = String::new();
    writeln!(script, "# Generated by cailoxo. Do not edit by hand.")?;
    writeln!(script, "# shell: pwsh")?;
    writeln!(script)?;
    write_consts(
        &mut script,
        os,
        path,
        git,
        prompt,
        transient_template,
        &os_style,
        &path_style,
        &git_clean_style,
        &git_dirty_style,
        RESET,
        &os_tail,
        &path_sep_clean,
        &path_sep_dirty,
        &path_sep_last,
        &git_sep_clean,
        &git_sep_dirty,
        &prompt_ok_style,
        &prompt_error_style,
        &transient_ok_style,
        &transient_error_style,
        config.final_space,
    )?;
    write_body(&mut script, transient_enabled)?;
    Ok(script)
}

#[allow(clippy::too_many_arguments)]
fn write_consts(
    out: &mut String,
    os: &Span,
    path: &Span,
    git: &Span,
    prompt: &Span,
    transient_template: &str,
    os_style: &str,
    path_style: &str,
    git_clean_style: &str,
    git_dirty_style: &str,
    reset: &str,
    os_tail: &str,
    path_sep_clean: &str,
    path_sep_dirty: &str,
    path_sep_last: &str,
    git_sep_clean: &str,
    git_sep_dirty: &str,
    prompt_ok_style: &str,
    prompt_error_style: &str,
    transient_ok_style: &str,
    transient_error_style: &str,
    final_space: bool,
) -> Result<()> {
    let min_dirs = path.setting_str("min_dirs").unwrap_or("1");
    let min_dirs = min_dirs.parse::<usize>().unwrap_or(1);
    let branch_icon = git_branch_icon(git)?;
    let fetch_upstream_icon = git.setting_bool("fetch_upstream_icon").unwrap_or(false);

    write_var(out, "CAILOXO_OS_TEMPLATE", &os.template)?;
    write_var(out, "CAILOXO_PATH_TEMPLATE", &path.template)?;
    write_var(out, "CAILOXO_GIT_TEMPLATE", &git.template)?;
    write_var(out, "CAILOXO_PROMPT_TEMPLATE", &prompt.template)?;
    write_var(out, "CAILOXO_TRANSIENT_TEMPLATE", transient_template)?;
    write_var(
        out,
        "CAILOXO_HOME_ICON",
        path.setting_str("home_icon").unwrap_or("~"),
    )?;
    write_var(
        out,
        "CAILOXO_FOLDER_ICON",
        path.setting_str("folder_icon").unwrap_or("…"),
    )?;
    write_var(
        out,
        "CAILOXO_EDGE_FORMAT",
        path.setting_str("edge_format").unwrap_or(""),
    )?;
    write_var(
        out,
        "CAILOXO_GITDIR_FORMAT",
        path.setting_str("gitdir_format").unwrap_or(""),
    )?;
    write_var(out, "CAILOXO_BRANCH_ICON", &branch_icon)?;
    write_var(out, "CAILOXO_STATUS_SEPARATOR", status_separator(git))?;
    writeln!(
        out,
        "$script:CAILOXO_FETCH_UPSTREAM_ICON = ${}",
        if fetch_upstream_icon { "true" } else { "false" }
    )?;
    writeln!(out, "$script:CAILOXO_MIN_DIRS = {min_dirs}")?;
    writeln!(
        out,
        "$script:CAILOXO_FINAL_SPACE = ${}",
        if final_space { "true" } else { "false" }
    )?;
    write_var(out, "CAILOXO_OS_STYLE", os_style)?;
    write_var(out, "CAILOXO_PATH_STYLE", path_style)?;
    write_var(out, "CAILOXO_GIT_CLEAN_STYLE", git_clean_style)?;
    write_var(out, "CAILOXO_GIT_DIRTY_STYLE", git_dirty_style)?;
    write_var(out, "CAILOXO_RESET", reset)?;
    write_var(out, "CAILOXO_OS_TAIL", os_tail)?;
    write_var(out, "CAILOXO_PATH_SEP_CLEAN", path_sep_clean)?;
    write_var(out, "CAILOXO_PATH_SEP_DIRTY", path_sep_dirty)?;
    write_var(out, "CAILOXO_PATH_SEP_LAST", path_sep_last)?;
    write_var(out, "CAILOXO_GIT_SEP_CLEAN", git_sep_clean)?;
    write_var(out, "CAILOXO_GIT_SEP_DIRTY", git_sep_dirty)?;
    write_var(out, "CAILOXO_PROMPT_OK_STYLE", prompt_ok_style)?;
    write_var(out, "CAILOXO_PROMPT_ERROR_STYLE", prompt_error_style)?;
    write_var(out, "CAILOXO_TRANSIENT_OK_STYLE", transient_ok_style)?;
    write_var(out, "CAILOXO_TRANSIENT_ERROR_STYLE", transient_error_style)?;

    write_status_templates(out, git)?;
    write_icon_map(out, "CAILOXO_OS_ICONS", "os", "nerdfont")?;
    write_icon_map(out, "CAILOXO_UPSTREAM_ICONS", "git_upstream", "nerdfont")?;
    Ok(())
}

fn write_var(out: &mut String, name: &str, value: &str) -> Result<()> {
    writeln!(out, "$script:{name} = {}", ps_string(value))?;
    Ok(())
}

fn write_status_templates(out: &mut String, git: &Span) -> Result<()> {
    writeln!(out, "$script:CAILOXO_STATUS_TEMPLATES = @{{")?;
    for status in STATUSES {
        writeln!(
            out,
            "  {} = {}",
            ps_string(status),
            ps_string(&status_template(git, status)?)
        )?;
    }
    writeln!(out, "}}")?;
    Ok(())
}

fn write_icon_map(out: &mut String, name: &str, group: &str, set: &str) -> Result<()> {
    writeln!(out, "$script:{name} = @{{")?;
    for (key, value) in icon_pairs(group, set)? {
        writeln!(out, "  {} = {}", ps_string(&key), ps_string(&value))?;
    }
    writeln!(out, "}}")?;
    Ok(())
}

fn write_body(out: &mut String, transient_enabled: bool) -> Result<()> {
    let body = r#"
$script:CAILOXO_PROMPT_TYPE = 'primary'

function Cailoxo-Plain-Template {
  param([string]$Text)
  $Text.Replace('<b>', '').Replace('</b>', '').Replace('<u>', '').Replace('</u>', '').Replace('<o>', '').Replace('</o>', '').Replace('<i>', '').Replace('</i>', '').Replace('<s>', '').Replace('</s>', '').Replace('<d>', '').Replace('</d>', '').Replace('<f>', '').Replace('</f>', '').Replace('<r>', '').Replace('</r>', '')
}

function Cailoxo-Style-Template {
  param([string]$Text)
  $esc = [char]27
  $Text.Replace('<b>', "$esc[1m").Replace('</b>', "$esc[22m").Replace('<u>', "$esc[4m").Replace('</u>', "$esc[24m").Replace('<o>', "$esc[53m").Replace('</o>', "$esc[55m").Replace('<i>', "$esc[3m").Replace('</i>', "$esc[23m").Replace('<s>', "$esc[9m").Replace('</s>', "$esc[29m").Replace('<d>', "$esc[2m").Replace('</d>', "$esc[22m").Replace('<f>', "$esc[5m").Replace('</f>', "$esc[25m").Replace('<r>', "$esc[7m").Replace('</r>', "$esc[27m")
}

function Cailoxo-Format-Part {
  param([string]$Value, [string]$Format)
  if ([string]::IsNullOrEmpty($Format)) { return $Value }
  if ($Format.Contains('%s')) { return $Format.Replace('%s', $Value) }
  $Value
}

function Cailoxo-Normalize-Path {
  param([string]$Path)
  if ($null -eq $Path) { return '' }
  $Path.Replace('\\', '/')
}

function Cailoxo-Home-Path {
  if (-not [string]::IsNullOrEmpty($HOME)) { return (Cailoxo-Normalize-Path $HOME) }
  Cailoxo-Normalize-Path ([Environment]::GetFolderPath('UserProfile'))
}

function Cailoxo-Git-Root-Name {
  $root = & git rev-parse --show-toplevel 2>$null
  if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace(($root -join ''))) { return '' }
  Split-Path -Leaf (($root -join "`n").Trim())
}

function Cailoxo-Format-Path {
  param([string]$Path, [string]$GitRoot)
  $prefix = ''
  $rest = $Path
  $absolute = $false
  if ($Path -eq '~') {
    return (Cailoxo-Format-Part $Path $script:CAILOXO_EDGE_FORMAT)
  } elseif ($Path.StartsWith('~/')) {
    $prefix = '~'
    $rest = $Path.Substring(2)
  } elseif ($Path.StartsWith('…/')) {
    $prefix = '…'
    $rest = $Path.Substring(2)
  } elseif ($Path.StartsWith('/')) {
    $absolute = $true
    $rest = $Path.Substring(1)
  }

  $parts = @($rest.Split([char[]]@('/'), [StringSplitOptions]::RemoveEmptyEntries))
  if ($absolute -and $parts.Count -eq 0) { return (Cailoxo-Format-Part '/' $script:CAILOXO_EDGE_FORMAT) }

  $out = @()
  if ($prefix -ne '') {
    if ($prefix -eq '…') { $out += $prefix } else { $out += (Cailoxo-Format-Part $prefix $script:CAILOXO_EDGE_FORMAT) }
  }

  for ($i = 0; $i -lt $parts.Count; $i++) {
    $raw = $parts[$i]
    $part = $raw
    if ($GitRoot -ne '' -and $raw -eq $GitRoot) { $part = Cailoxo-Format-Part $part $script:CAILOXO_GITDIR_FORMAT }
    if ($i -eq ($parts.Count - 1) -or ($i -eq 0 -and $out.Count -eq 0)) { $part = Cailoxo-Format-Part $part $script:CAILOXO_EDGE_FORMAT }
    $out += $part
  }

  $joined = $out -join '/'
  if ($absolute) { '/' + $joined } else { $joined }
}

function Cailoxo-Shorten-Path {
  param([int]$Budget)
  $cwd = Cailoxo-Normalize-Path ((Get-Location).ProviderPath)
  $homePath = Cailoxo-Home-Path
  if ($cwd -eq $homePath) {
    $display = '~'
  } elseif ($homePath -ne '' -and $cwd.StartsWith($homePath + '/')) {
    $display = '~' + $cwd.Substring($homePath.Length)
  } else {
    $display = $cwd
  }

  if ($display.Length -le $Budget) { return $display }
  if ($display.StartsWith('~/')) {
    $prefix = '~'
    $rest = $display.Substring(2)
  } elseif ($display.StartsWith('/')) {
    $prefix = ''
    $rest = $display.Substring(1)
  } else {
    $prefix = ''
    $rest = $display
  }

  $parts = @($rest.Split([char[]]@('/'), [StringSplitOptions]::RemoveEmptyEntries))
  if ($parts.Count -eq 0) { return $display }
  $current = $parts[$parts.Count - 1]
  if ($Budget -le 4) { return "…/$current" }
  if ($parts.Count -ge 2) {
    $candidate = "$(if ($prefix -ne '') { "$prefix/" })…/$($parts[$parts.Count - 2])/$current"
    if ($candidate.Length -le $Budget) { return $candidate }
  }
  $candidate = "$(if ($prefix -ne '') { "$prefix/" })…/$current"
  if ($candidate.Length -le $Budget) { return $candidate }
  "…/$current"
}

function Cailoxo-Os-Icon {
  $id = 'unknown'
  if ($IsWindows) {
    $id = 'windows'
  } elseif ($IsMacOS) {
    $id = 'macos'
  } elseif (Test-Path '/etc/os-release') {
    foreach ($line in Get-Content '/etc/os-release' -ErrorAction SilentlyContinue) {
      if ($line.StartsWith('ID=')) {
        $id = $line.Substring(3).Trim('"').ToLowerInvariant()
        break
      }
    }
  }
  if ($script:CAILOXO_OS_ICONS.ContainsKey($id)) { return $script:CAILOXO_OS_ICONS[$id] }
  $script:CAILOXO_OS_ICONS['unknown']
}

function Cailoxo-Upstream-Provider {
  param([string]$Url)
  $normalized = $Url.ToLowerInvariant()
  if ($normalized.Contains('github.com')) { return 'github' }
  if ($normalized.Contains('gitlab.com')) { return 'gitlab' }
  if ($normalized.Contains('bitbucket.org')) { return 'bitbucket' }
  if ($normalized.Contains('codeberg.org')) { return 'codeberg' }
  if ($normalized.Contains('gitea')) { return 'gitea' }
  if ($normalized.Contains('dev.azure.com') -or $normalized.Contains('visualstudio.com')) { return 'azure_devops' }
  ''
}

function Cailoxo-Upstream-Info {
  param([string]$Branch)
  $info = @{ upstream = ''; upstream_icon = ''; upstream_url = '' }
  if (-not $script:CAILOXO_FETCH_UPSTREAM_ICON) { return $info }
  $remote = (& git config --get "branch.$Branch.remote" 2>$null) -join ''
  if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($remote)) { $remote = 'origin' }
  $url = (& git config --get "remote.$remote.url" 2>$null) -join ''
  if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($url)) { return $info }
  $upstream = Cailoxo-Upstream-Provider $url.Trim()
  $icon = if ($upstream -ne '' -and $script:CAILOXO_UPSTREAM_ICONS.ContainsKey($upstream)) { $script:CAILOXO_UPSTREAM_ICONS[$upstream] } else { '' }
  @{ upstream = $upstream; upstream_icon = $icon; upstream_url = $url.Trim() }
}

function Cailoxo-Apply-Template {
  param([string]$Template, [hashtable]$Vars)
  $tpl = $Template
  $marker = '{{ if status }}'
  $endMarker = '{{ end }}'
  $elseMarker = '{{ else }}'
  while ($tpl.Contains($marker)) {
    $start = $tpl.IndexOf($marker)
    $before = $tpl.Substring(0, $start)
    $rest = $tpl.Substring($start + $marker.Length)
    $end = $rest.IndexOf($endMarker)
    if ($end -lt 0) { break }
    $body = $rest.Substring(0, $end)
    $after = $rest.Substring($end + $endMarker.Length)
    $else = $body.IndexOf($elseMarker)
    if ($else -ge 0) {
      $thenPart = $body.Substring(0, $else)
      $elsePart = $body.Substring($else + $elseMarker.Length)
    } else {
      $thenPart = $body
      $elsePart = ''
    }
    $status = if ($Vars.ContainsKey('status')) { [string]$Vars['status'] } else { '' }
    $tpl = $before + $(if ($status -ne '') { $thenPart } else { $elsePart }) + $after
  }

  foreach ($key in @('icon', 'path', 'home_icon', 'folder_icon', 'status', 'branch_icon', 'upstream_icon', 'upstream', 'upstream_url', 'branch')) {
    $value = if ($Vars.ContainsKey($key)) { [string]$Vars[$key] } else { '' }
    $tpl = $tpl.Replace("{{ $key }}", $value)
  }
  $tpl
}

function Cailoxo-Path-Template {
  param([hashtable]$Vars)
  $marker = '{{ if home }}'
  if (-not $script:CAILOXO_PATH_TEMPLATE.Contains($marker)) {
    return (Cailoxo-Apply-Template $script:CAILOXO_PATH_TEMPLATE $Vars)
  }
  $start = $script:CAILOXO_PATH_TEMPLATE.IndexOf($marker)
  $before = $script:CAILOXO_PATH_TEMPLATE.Substring(0, $start)
  $rest = $script:CAILOXO_PATH_TEMPLATE.Substring($start + $marker.Length)
  $else = $rest.IndexOf('{{ else }}')
  $end = $rest.IndexOf('{{ end }}')
  if ($else -lt 0 -or $end -lt 0) { return (Cailoxo-Apply-Template $script:CAILOXO_PATH_TEMPLATE $Vars) }
  $homePart = $rest.Substring(0, $else)
  $otherPart = $rest.Substring($else + '{{ else }}'.Length, $end - ($else + '{{ else }}'.Length))
  $after = $rest.Substring($end + '{{ end }}'.Length)
  $body = if ($Vars['home']) { $homePart } else { $otherPart }
  Cailoxo-Apply-Template ($before + $body + $after) $Vars
}

function Cailoxo-Status-Item {
  param([string]$Name, [int]$Count)
  if ($Count -le 0) { return '' }
  $script:CAILOXO_STATUS_TEMPLATES[$Name].Replace('{{ count }}', [string]$Count)
}

function Cailoxo-Count-Command {
  param([scriptblock]$Block)
  $raw = & $Block 2>$null
  if ($LASTEXITCODE -ne 0) { return 0 }
  $value = 0
  if ([int]::TryParse((($raw -join '').Trim()), [ref]$value)) { return $value }
  0
}

function Cailoxo-Git-Info {
  $empty = @{ branch = ''; status = ''; dirty = $false; upstream = ''; upstream_icon = ''; upstream_url = '' }
  $inside = (& git rev-parse --is-inside-work-tree 2>$null) -join ''
  if ($LASTEXITCODE -ne 0 -or $inside.Trim() -ne 'true') { return $empty }

  $branch = (& git symbolic-ref --quiet --short HEAD 2>$null) -join ''
  if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($branch)) {
    $branch = (& git rev-parse --short HEAD 2>$null) -join ''
  }
  $branch = $branch.Trim()
  if ($branch -eq '') { return $empty }
  $upstream = Cailoxo-Upstream-Info $branch

  $counts = @{ ahead = 0; behind = 0; conflicted = 0; untracked = 0; modified = 0; staged = 0; renamed = 0; deleted = 0; stashed = 0 }
  $status = & git status --porcelain=v1 2>$null
  foreach ($line in @($status)) {
    if ([string]::IsNullOrEmpty($line) -or $line.Length -lt 2) { continue }
    $code = $line.Substring(0, 2)
    if ($code -eq '??') { $counts.untracked++; continue }
    if (@('DD', 'AU', 'UD', 'UA', 'DU', 'AA', 'UU') -contains $code) { $counts.conflicted++; continue }
    $x = $line.Substring(0, 1)
    $y = $line.Substring(1, 1)
    if ($x -eq 'R') { $counts.renamed++ }
    if ($x -eq 'D' -or $y -eq 'D') { $counts.deleted++ }
    if ($x -ne ' ' -and $x -ne 'R' -and $x -ne 'D') { $counts.staged++ }
    if ($y -ne ' ' -and $y -ne 'D') { $counts.modified++ }
  }

  $counts.ahead = Cailoxo-Count-Command { git rev-list --count '@{upstream}..HEAD' }
  $counts.behind = Cailoxo-Count-Command { git rev-list --count 'HEAD..@{upstream}' }
  $stash = & git stash list 2>$null
  if ($LASTEXITCODE -eq 0) { $counts.stashed = @($stash | Where-Object { $_ -ne '' }).Count }

  $items = @()
  foreach ($name in @('ahead', 'behind', 'conflicted', 'untracked', 'modified', 'staged', 'renamed', 'deleted', 'stashed')) {
    $item = Cailoxo-Status-Item $name $counts[$name]
    if ($item -ne '') { $items += $item }
  }
  @{ branch = $branch; status = ($items -join $script:CAILOXO_STATUS_SEPARATOR); dirty = ($items.Count -gt 0); upstream = $upstream.upstream; upstream_icon = $upstream.upstream_icon; upstream_url = $upstream.upstream_url }
}

function Cailoxo-Render-Full {
  param([int]$LastStatus)
  $osIcon = Cailoxo-Os-Icon
  $git = Cailoxo-Git-Info
  $gitRoot = Cailoxo-Git-Root-Name
  $gitVars = @{ status = $git.status; branch_icon = $script:CAILOXO_BRANCH_ICON; upstream_icon = $git.upstream_icon; upstream = $git.upstream; upstream_url = $git.upstream_url; branch = $git.branch }
  $gitText = if ($git.branch -eq '') { '' } else { Cailoxo-Apply-Template $script:CAILOXO_GIT_TEMPLATE $gitVars }
  $osText = Cailoxo-Apply-Template $script:CAILOXO_OS_TEMPLATE @{ icon = $osIcon }

  $width = 80
  try { $width = [Console]::WindowWidth } catch {}
  if ($width -le 0) { $width = 80 }
  $fixed = (Cailoxo-Plain-Template $osText).Length + (Cailoxo-Plain-Template $gitText).Length + $script:CAILOXO_HOME_ICON.Length + $script:CAILOXO_FOLDER_ICON.Length + 10
  $budget = [Math]::Max(1, $width - $fixed)
  $path = Cailoxo-Format-Path (Cailoxo-Shorten-Path $budget) $gitRoot
  $homePath = Cailoxo-Home-Path
  $isHome = (Cailoxo-Normalize-Path ((Get-Location).ProviderPath)) -eq $homePath
  $pathText = Cailoxo-Path-Template @{ path = $path; home = $isHome; home_icon = $script:CAILOXO_HOME_ICON; folder_icon = $script:CAILOXO_FOLDER_ICON }

  $gitStyle = if ($git.dirty) { $script:CAILOXO_GIT_DIRTY_STYLE } else { $script:CAILOXO_GIT_CLEAN_STYLE }
  $pathSep = if ($gitText -eq '') { $script:CAILOXO_PATH_SEP_LAST } elseif ($git.dirty) { $script:CAILOXO_PATH_SEP_DIRTY } else { $script:CAILOXO_PATH_SEP_CLEAN }
  $gitSep = if ($git.dirty) { $script:CAILOXO_GIT_SEP_DIRTY } else { $script:CAILOXO_GIT_SEP_CLEAN }
  $first = $script:CAILOXO_OS_STYLE + (Cailoxo-Style-Template $osText) + $script:CAILOXO_RESET + $script:CAILOXO_OS_TAIL
  $first += $script:CAILOXO_PATH_STYLE + (Cailoxo-Style-Template $pathText) + $script:CAILOXO_RESET + $pathSep
  if ($gitText -ne '') { $first += $gitStyle + (Cailoxo-Style-Template $gitText) + $script:CAILOXO_RESET + $gitSep }

  $promptStyle = if ($LastStatus -eq 0) { $script:CAILOXO_PROMPT_OK_STYLE } else { $script:CAILOXO_PROMPT_ERROR_STYLE }
  $suffix = if ($script:CAILOXO_FINAL_SPACE) { ' ' } else { '' }
  $first + "`n" + $promptStyle + (Cailoxo-Style-Template $script:CAILOXO_PROMPT_TEMPLATE) + $script:CAILOXO_RESET + $suffix
}

function Cailoxo-Render-Transient {
  param([int]$LastStatus)
  $promptStyle = if ($LastStatus -eq 0) { $script:CAILOXO_TRANSIENT_OK_STYLE } else { $script:CAILOXO_TRANSIENT_ERROR_STYLE }
  $promptStyle + (Cailoxo-Style-Template $script:CAILOXO_TRANSIENT_TEMPLATE) + $script:CAILOXO_RESET
}

function prompt {
  $originalSuccess = $?
  $originalLastExitCode = $global:LASTEXITCODE
  $lastStatus = if ($originalSuccess) { 0 } elseif ($null -ne $originalLastExitCode) { [int]$originalLastExitCode } else { 1 }
  if ($script:CAILOXO_PROMPT_TYPE -eq 'transient') {
    $script:CAILOXO_PROMPT_TYPE = 'primary'
    $output = Cailoxo-Render-Transient $lastStatus
  } else {
    $output = Cailoxo-Render-Full $lastStatus
  }
  try { Set-PSReadLineOption -ExtraPromptLineCount ((($output -split "`n").Count) - 1) } catch {}
  $global:LASTEXITCODE = $originalLastExitCode
  $output
}
"#;
    out.push_str(body);

    if transient_enabled {
        out.push_str(
            r#"
function Set-CailoxoTransientPrompt {
  $script:CAILOXO_PROMPT_TYPE = 'transient'
  try { [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt() } catch {}
}

try {
  Set-PSReadLineKeyHandler -Key Enter -BriefDescription 'CailoxoEnterKeyHandler' -ScriptBlock {
    try {
      $parseErrors = $null
      [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$null, [ref]$null, [ref]$parseErrors, [ref]$null)
      if ($null -eq $parseErrors -or $parseErrors.Count -eq 0) { Set-CailoxoTransientPrompt }
    } finally {
      [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
    }
  }
} catch {}
"#,
        );
    }

    Ok(())
}

fn edge(
    glyph: Option<&str>,
    fg: Option<&String>,
    bg: Option<&String>,
    invert: bool,
) -> Result<String> {
    let Some(glyph) = glyph else {
        return Ok(String::new());
    };
    let mut out = String::new();
    let (fg, bg) = if invert { (bg, fg) } else { (fg, bg) };
    out.push_str(&color_escape(fg, false)?);
    out.push_str(&color_escape(bg, true)?);
    out.push_str(glyph);
    out.push_str(RESET);
    Ok(out)
}

fn ps_string(input: &str) -> String {
    format!("'{}'", input.replace('\'', "''"))
}

#[cfg(test)]
mod tests {
    use crate::config::Config;

    use super::*;

    #[test]
    fn generates_pwsh() {
        let config = Config::parse(include_str!("../../cailoxo.toml")).unwrap();
        let script = generate(&config).unwrap();
        assert!(script.contains("function Cailoxo-Git-Info"));
        assert!(script.contains("function Cailoxo-Style-Template"));
        assert!(script.contains("function Cailoxo-Format-Path"));
        assert!(script.contains("Set-PSReadLineKeyHandler"));
        assert!(script.contains("function prompt"));
    }
}
